# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-28 02:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 2, 6, 7, 882996, tzinfo=utc)),
        ),
    ]
