# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-28 02:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190328_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 2, 31, 1, 696815, tzinfo=utc)),
        ),
    ]
